#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/wangkangas/ConfigCenter
#          username: 1120191863@qq.com
#          password: 665821wkk
#          #default
#      profile: v1
#      label: ConfigCenter
#      name: config-server-v1.yml
#  #search-paths: /tree/ConfigCenter
#  application:
#    name: config-server
#server:
#  port: 4000
#

#eureka:
#  client:
#    service-url:
#        defaultZone: http://localhost:1111/eureka

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
      #name: config-server
      #profile: v1
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 4000